apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastk8s-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastk8s
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
